server:
  port: 8081
spring:
  cloud:
    config:
      server:
        git:
          default-label: eureka-server
          uri: https://github.com/EraniaG/microservice-pratice
          search-paths: config-data
  application:
    name: config-server